### ISSUE TITLE
[Bug]: <Brief description of the bug> chat bot 

### ISSUE THREAD

**Issue by yogeswari05** [Ajay-Dhangar/algo#1002]
### Bug Summary

Chatbot is not responding.

### Bug Description

![image](https://github.com/user-attachments/assets/c58157e1-ce0e-4c9b-a3da-9c33f434b2b5)

### Steps to Reproduce

I would like to deep dive into its working then correct and enhance its performance.

### Expected Behavior

It should be responding to the user requests or messages.

### Screenshots or Logs (Optional)

![image](https://github.com/user-attachments/assets/d1f20f84-2566-4e2b-ae7d-fcbc94ea00e6)
![image](https://github.com/user-attachments/assets/fc590f42-6f2b-40af-9c49-a2e4084e256a)

### Severity

Critical - prevents the use of the system

### Environment

- [ ] Local Development
- [ ] Staging
- [ ] Production
- [ ] Other

**Comment by ajay-dhangar** [comment]
I know because I put only a few inputs in my model, but if I were free, I would try to make a large response model for different questions. You can't work on this directly, so can you provide me with some examples of questions that users might ask a chat bot? I can then use these examples to create a model. Please provide these examples in the discussion section.

**Comment by yogeswari05** [comment]
Ok, I got it.
Here are some examples:
what is DSA
How can I get started with DSA
DSA roadmap
DSA practice questions
What is so and so algorithm
...etc

**Comment by ajay-dhangar** [comment]
You can try our available response for inputs
- Do you have a beginner’s guide?
- Hi
- How do I get started with Algo?
- What is Algo
- What can I find on the homepage?
