### ISSUE TITLE
[Bug] BackToTop Button Misfunctioning 

### ISSUE THREAD

**Issue by Shariq2003** [Ajay-Dhangar/algo#364]
### Describe the bug
The BackToTop button only appears when we scroll to upwards, instead of appearing when user scroll down some height and  also at the bottom, which makes surety to let the user  know  about the BackToTop functionality.

Also refer to video for detail.

https://github.com/user-attachments/assets/88d51d34-0153-41fd-88a1-708fcfa31215

---

**Would you like to work on this issue?**  
- [X] Yes  
- [ ] No

**Comment by ajay-dhangar** [comment]
If you are comfortable with the default settings and understand them, then go ahead and work on the issue. However, if you are inexperienced, then I can't ask you to try it because I am very busy right now debugging all the PR's code and helping everyone. I don't want to make things more complicated for you or me.
